### ISSUE TITLE
Installing 2.0.1 via NuGet gives dependency errors for RestSharp

### ISSUE THREAD

**Issue by victor-pme** [plivo/plivo-dotnet#25] opened 2015-11-19 04:57 UTC
Error CS0012: The type `RestSharp.IRestResponse`1<Plivo.API.MessageResponse>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `RestSharp, Version=105.1.0.0, Culture=neutral, PublicKeyToken=null' (CS0012) (pM.Api)

I can see the _RestSharpSigned_ package has been included, but it looks like it still needs the _RestSharp_ package to also be included.

If I manually add the _RestSharp_ package it works, but we shouldn't have to add packages manually.

**Comment by jcpm** [comment] 2015-11-19 04:59
I can confirm that this happens both on xamarin studio (mono) and windows / visual studio.

**Comment by sdebnath** [comment] 2015-11-19 05:03
Did you have previous references to the RestSharp assembly in the solution? Could you try removing the references and the Plivo nuget packages and reinstalling them followed with a build to see if it repros?

**Comment by victor-pme** [comment] 2015-11-19 05:05
@sdebnath no I didn't have any previous references to RestSharp. In fact when I install 2.0.0 and then upgrade to 2.0.1, it _removes_ the RestSharp package!

**Comment by sdebnath** [comment] 2015-11-19 05:17
Yes, thats expected as Plivo will install the RestSharpSigned package as a dependency instead of bundling the RestSharp.dll. RestSharpSigned nuget package installs RestSharp.dll (same DLL name that is installed by the regular RestSharp nuget package). Can you ensure that the projects where you installed the nuget package to has the references for RestSharp and they should be pointing to RestSharp dll in the nuget packages directory in your project. 

Ex: packages\RestSharp.105.1.0\lib\net4\RestSharp.dll

If the path for the reference is empty, can you confirm that packages directory contains RestSharp.105.1.0 and not RestSharpSigned.105.1.0? The Plivo project provides a hint path to that directory. If the dir has been renamed, the hint wont work and will likely result in the error you are seeing. 

Thanks.

**Comment by victor-pme** [comment] 2015-11-19 05:25
Are you saying I need to manually add the reference to RestSharp.dll manually?

The packages directory has RestSharpSigned.105.0.1
I don't see RestSharp.105.0.1

**Comment by sdebnath** [comment] 2015-11-19 05:30
Nope you shouldn't have to add the reference manually (for normal consumption). Somehow I pushed up the change to the project file with the wrong directory and everyone managed to test it fine. 

The issue is here: https://github.com/plivo/plivo-dotnet/blob/master/Plivo/Plivo.csproj#L37

The HintPath should be "<HintPath>packages\RestSharpSigned.105.1.0\lib\net4\RestSharp.dll</HintPath>".

Would appreciate it if you can confirm that though :)

If you can, feel free to update the project file and send up a PR and @tsudot can take a look at it. You can also build the nuget and import the nuget manually into your solution for testing (or use it till the official fix is out).

**Comment by victor-pme** [comment] 2015-11-19 05:56
When will the official fix be available?

**Comment by Ramya-Raghu** [comment] 2015-11-25 15:45
@victor-pme and @sdebnath - We have just pushed the fix for the RestSharpSigned dependency issue. Can you please review? We will publish this on NuGet in a couple of days.

**Comment by sdebnath** [comment] 2015-11-28 21:20
@Ramya-Raghu got a link to the PR, branch, or commit?

**Comment by Ramya-Raghu** [comment] 2015-11-29 05:20
@sdebnath The changes were pushed to extra-params branch - https://github.com/plivo/plivo-dotnet/tree/extra-params

**Comment by sdebnath** [comment] 2015-11-29 20:23
Plivo/Plivo.csproj changes in that commit look good.

**Comment by Ramya-Raghu** [comment] 2015-12-22 07:58
Merged and pushed to NuGet.

**Closed by Ramya-Raghu** 2015-12-22 07:58 UTC

**Comment by scushen** [comment] 2016-01-29 15:34
Still getting this error with the latest release
